version: "3.8"
services:
    api:
        container_name: api
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 8080:8080
        depends_on:
            - database
    database:
        container_name: database
        restart: unless-stopped
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=laradash
            - MYSQL_USER=laradashdb
            - MYSQL_PASSWORD=laradashdb
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - db-data:/var/lib/mysql
            - ./docker/mysql:/docker-entrypoint-initdb.d
volumes:
    db-data: ~
